# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
loader_version=0.19.3
# Mod Properties
mod_version=1.0.1
maven_group=me.sootysplash.dm
archives_base_name=arrow-indicator

# Dependencies
# check this on https://modmuss50.me/fabric.html

#minecraft_version=1.21.11
#fabric_version=0.141.5+1.21.11
#modmenu_version=17.0.0
#cloth_config_version=21.11.153

minecraft_version=1.21.6
fabric_version=0.128.2+1.21.6
modmenu_version=15.0.2
cloth_config_version=19.0.147